name: Build Paper
on:
  workflow_dispatch:
    inputs:
      pr:
        description: PR number to build
        required: true

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [17]
            fail-fast: true
        steps:
            - uses: actions/checkout@v2.4.0
            - name: JDK ${{ matrix.java }}
              uses: actions/setup-java@v3.1.0
              with:
                  java-version: ${{ matrix.java }}
                  distribution: temurin
            - name: Clone, patch and build PR ${{ github.event.inputs.pr }}
              run: |                   
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "Github Actions"
                  git clone https://github.com/PaperMC/Paper.git
                  cd Paper
                  git fetch origin pull/${{ github.event.inputs.pr }}/head && git checkout FETCH_HEAD
                  git am -3 < ../repo.patch
                  ./gradlew applyPatches --stacktrace
                  ./gradlew build Paper-API:publish --stacktrace
                  ./gradlew createMojmapPaperclipJar --stacktrace
                  ./gradlew createReobfPaperclipJar --stacktrace
            - uses: actions/upload-artifact@v3
              with:
                name: api
                path: Paper/Paper-API/maven-repository
            - uses: actions/upload-artifact@v3
              with:
                name: paperclips
                path: Paper/build/libs/paper-paperclip-*.jar
